// <auto-generated />
namespace SORT_doc_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201707290819317_assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
