// <auto-generated />
namespace SORT_doc_app.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nonulldatesummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonulldatesummary));
        
        string IMigrationMetadata.Id
        {
            get { return "201707272225075_nonulldatesummary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
